server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index /index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend:5000;
    }

    # Permettre les gros uploads (c'est pour plus tard que je met ceci là)
    client_max_body_size 10m;
}